### ISSUE TITLE
masterpassword considerations

### ISSUE THREAD

**Issue by sarahavilov** [web-ext-experiments/logins#14]
There are two things regarding the master password support that I would like to propose which are going to help me port my Secure Login add-on.

1. A method that returns whether the master password is already entered by user and the database is accessible or not; basically a function that returns `nsILoginManager.isLoggedIn`

2. A listener that notifies the extension when the master password is entered and the database is open. Something like 
```js
browser.logins.addListener('master-password', (bol) => console.log(bol));
```

Please note that some extensions like Master Password + can disconnect the database directly and hence user will need to re-enter the master password one more time to have access to the database. Knowing whether the database is logged-in or logged-out is useful in extensions.

**Comment by bobsilverberg** [comment]
@sarahavilov I'm not sure if these fit into our vision for the logins API or not, but regardless we are discontinuing development of this API as an experiment and the logins API is going to be added as a built-in API for Firefox. You can follow the development of that at [1].

Because of that, GitHub is no longer the appropriate place to raise issues like this. Can you please file a Bugzilla bug for this request?

[1] https://bugzil.la/1324919
