### ISSUE TITLE
Why no callback?

### ISSUE THREAD

**Issue by brunoais** [web-ext-experiments/logins#9]
Why are there no options to get a callback with the result?

Personally, I don't have anything against Promises paradigm but I still prefer using the callback paradygm. May that also be available to web extensions?

**Comment by andymckay** [comment]
We haven't really talked about if that would be a good standard to support in all the new APIs that we land, this is one of the first. I can imagine maintaining both is a bit of a pain long term and personally think we should aim to just go with promises.

Whats the cost in terms of code of maintaining both?
Whats the advantage?

**Comment by kmaglione** [comment]
There's not really any point to supporting both. The W3 group has decided on promises rather than callbacks for all standardized APIs, so there's not much point in supporting callbacks outside of Chrome compatibility stubs. If you really want to use callbacks instead, you can always write a polyfill.

**Comment by brunoais** [comment]
OK. Got it.
